### PR TITLE
Allow deletion of old backups in zip mode

### PR DESCRIPTION
**Pull request by sdaguet**
Initially worked only for .dump files

### CODE REVIEW

**Comment by funbaker** [comment]
This prevents old files from deletion and is breaking, especially on restricted backup space

**Comment by sdaguet** [comment]
Not deleting zip backup files is also breaking, especially on restricted backup space ;)

**Comment by funbaker** [comment]
Damn... I wrote a comment in a confusing way again, aye?

s/This prevents old files/The Bug that this PR is fixing prevents old files/

**Comment by sdaguet** [comment]
Understood ;)

 

I see it is corrected in 10.0 and master branches.

Do you want me to prepare a new pull request or you can update directly (.dump or .zip) ?

 

Stéphane

**Comment by Yenthe666** [comment]
Hi @sdaguet,

Thanks a lot for your PR but I do not really agree with it.
Your PR will look at the type that is configured under your settings. Imagine that you've had the module take back-ups from the type .zip for 29 days and today you switch to the type .dump. With your PR it'll delete all database that contain .dump in this case but all the ones that are of the type .zip will be skipped, since the type does not match.
In V10 I made a fix for this anyways and I specifically added in .dump **and** .zip, which you can see here: https://github.com/Yenthe666/auto_backup/blob/10.0/auto_backup/models/db_backup.py#L235
Wouldn't it be better to keep this and to backport it to the 8.0 and 9.0 version?

Regards,
Yenthe

**Pull request closed without merging**
