### PR TITLE
[REF] auto_backup: Refactor command execution in auto_backup module

### PR DESCRIPTION
**Pull request by randall-vx**
To avoid error with:
DeprecationWarning: Since 16.0, use `subprocess` directly.

Details:
- Added `subprocess` import.
- Replaced `odoo.tools.exec_pg_command` with `subprocess.run` in `_dump_db_manifest`.
- Replaced `odoo.tools.exec_pg_command_pipe` with `subprocess.Popen`.
- Changed `insert` to `append` for command list modification.

### CODE REVIEW

**Comment by randall-vx** [comment]
Hi @Yenthe666 ! Hope you are Ok !

Could you review please?

regards,

**Comment by Yenthe666** [comment]
Hey @randall-vx! All good here, hope you are too? :) Thanks for making a PR!
I haven't functionally tested it because I don't have enough time right now but your code looks good by the looks of it.
Has it been tested on an instance at your end?

**Comment by randall-vx** [comment]
Hi @Yenthe666 

Functionally tested in a dev docker container

## Before this change

#### Backup configuration

Screenshot 2024-03-19 at 2 59 31 PM

#### Backup error 

Screenshot 2024-03-19 at 3 04 04 PM

#### File size in backup path

Screenshot 2024-03-19 at 3 08 57 PM

## After this change

#### Backup creation

Screenshot 2024-03-19 at 3 05 02 PM

#### File size in backup path

Screenshot 2024-03-19 at 3 05 21 PM

#### Removed database and restored from zip file 

Screenshot 2024-03-19 at 3 17 42 PM

## Restored database

#### Database backups

Screenshot 2024-03-19 at 3 28 43 PM

Commands used

```bash
unzip 2024_03_19_21_04_39_odoo.zip
createdb odoo
psql -f dump.sql odoo
```

#### Database

Screenshot 2024-03-19 at 3 33 40 PM

#### Functionally
Screenshot 2024-03-19 at 3 35 50 PM

#### Update all addons

```bash
$ ~/instance/odoo/odoo-bin -c ~/.openerp_serverrc -d odoo --db-filter=odoo --log-level=critical -u all
```

Screenshot 2024-03-19 at 3 37 51 PM

Let me know if you have any questions!

regards,

**Comment by Yenthe666** [comment]
Thanks for the detailed response and the PR! I've merged it in 🥳 Great work!
P.S: Welcome to do it for V17 too if you need it/want it.

**Pull request merged**
