### PR TITLE
Upgrade auto_backup from v16 to v17

### PR DESCRIPTION
**Pull request by renelhs**
- Important: SFTP was not tested.

### CODE REVIEW

**Comment by renelhs** [comment]
@Yenthe666, can you please review this? Thanks.

**Comment by Yenthe666** [comment]
@renelhs hey! Thanks a lot for your PR :) Doing this however would change our code for Odoo 16.0 while we want it for 17.0.
I made a 17.0 branch (https://github.com/Yenthe666/auto_backup/tree/17.0) so you can do the pull request against this. That should work fine :)

**Comment by renelhs** [comment]
@Yenthe666 it's done, greetings.

**Comment by Yenthe666** [comment]
Thanks a lot @renelhs 👍 🙏

**Pull request merged**
