### PR TITLE
calling transport.keep_alive to prevent socket closed / connection dropped error

### PR DESCRIPTION
**Pull request by funbaker**
Hello,

i made this change in order to fix a annoying bug which prevents a successfull backup with oddly configured ssh/sftp servers, and i hope it will be useful :)

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hi @funbaker 

Thanks for this pull request. If I understand this correctly it will keep the FTP call open from one server to another if nothing is being sent within 30 seconds. It will then send a packet to keep the connection open? What I wonder myself is.. will this close the session after 30 seconds without anything being sent or am I wrong here? What is the default time-out?

Sorry for all the questions but I want to be sure I don't break anything and/or don't make any nasty side effects!

**Comment by funbaker** [comment]
Some more information :)
https://github.com/paramiko/paramiko/issues/151

Some SSH Servers are dropping the connection in inactivity. For example, you can run a program which generates output but the connection will still drop if you just keep watchin. 

transport.set_keepalive(n) sends a keepalive paket (dont ask me for protocol details :) ), which should keep the connection open.
http://paramiko-docs.readthedocs.org/en/latest/api/transport.html#paramiko.transport.Transport.set_keepalive

Maybe its a good idea to make this configurable, because the error still occured tonight, but only once instead of everytime :)

**Comment by Yenthe666** [comment]
Hmm very interesting.. Alright I will tinker around a bit with this soon :smile: 
Thanks @funbaker! I'll keep you updated :+1:

**Comment by Yenthe666** [comment]
@funbaker I let it run for a few nights and everything seems to be working fine. Couldn't find any problems with this so I've added it in. Once again, thanks a lot :+1: 
If you ever notice problems or have more ideas let me know!

**Pull request merged**
